// Generated by npm run build.
window.__ModuleLoader__.load({
  id: '@lolkda/dsh-retry',
  factory(require) {
    const module = { exports: {} };
    const exports = module.exports;
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client.js
var client_exports = {};
__export(client_exports, {
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(client_exports);
var import_react2 = __toESM(require("react"), 1);

// src/policy.js
var MODE_NORMAL = "normal";
var MODE_ALWAYS = "always";
var MAX_TIMER_DELAY_MS = 2147483647;
var DEFAULT_RETRYABLE_CODES = Object.freeze([
  "EMPTY_RESPONSE",
  "RATE_LIMIT",
  "SERVER",
  "TIMEOUT",
  "TRANSPORT"
]);
var DEFAULT_BACKOFF = Object.freeze({ initialDelayMs: 500, maxDelayMs: 1e4, jitterRatio: 0.1 });
var DEFAULT_POLICY = Object.freeze({
  mode: MODE_NORMAL,
  maxRetries: 5,
  retryableCodes: DEFAULT_RETRYABLE_CODES,
  backoff: DEFAULT_BACKOFF
});
var NORMAL_KEYS = /* @__PURE__ */ new Set(["mode", "maxRetries", "retryableCodes", "backoff"]);
var ALWAYS_KEYS = /* @__PURE__ */ new Set(["mode", "maxRetries", "retryableCodes", "backoff"]);
var BACKOFF_KEYS = /* @__PURE__ */ new Set(["initialDelayMs", "maxDelayMs", "jitterRatio"]);
var NORMAL_POLICY_FIELDS = { maxRetries: 5, retryableCodes: DEFAULT_RETRYABLE_CODES };
function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function assertKnownKeys(value, allowed, path) {
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) throw new Error(`${path}: unknown key ${JSON.stringify(key)}`);
  }
}
function resolveBackoff(config, path) {
  if (config !== void 0 && !isPlainObject(config)) throw new Error(`${path} must be an object or undefined`);
  if (config !== void 0) assertKnownKeys(config, BACKOFF_KEYS, path);
  const initialDelayMs = config?.initialDelayMs ?? DEFAULT_BACKOFF.initialDelayMs;
  const maxDelayMs = config?.maxDelayMs ?? DEFAULT_BACKOFF.maxDelayMs;
  const jitterRatio = config?.jitterRatio ?? DEFAULT_BACKOFF.jitterRatio;
  if (!Number.isFinite(initialDelayMs) || initialDelayMs <= 0 || initialDelayMs > MAX_TIMER_DELAY_MS) {
    throw new Error(`${path}.initialDelayMs must be a positive finite number no greater than ${MAX_TIMER_DELAY_MS}`);
  }
  if (!Number.isFinite(maxDelayMs) || maxDelayMs <= 0 || maxDelayMs > MAX_TIMER_DELAY_MS) {
    throw new Error(`${path}.maxDelayMs must be a positive finite number no greater than ${MAX_TIMER_DELAY_MS}`);
  }
  if (initialDelayMs > maxDelayMs) {
    throw new Error(`${path}.initialDelayMs must be less than or equal to maxDelayMs`);
  }
  if (typeof jitterRatio !== "number" || !Number.isFinite(jitterRatio) || jitterRatio < 0 || jitterRatio > 1) {
    throw new Error(`${path}.jitterRatio must be between 0 and 1`);
  }
  return { initialDelayMs, maxDelayMs, jitterRatio };
}
function resolveRetryableCodes(value) {
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error("policy.retryableCodes must not be empty");
  }
  for (const code of value) {
    if (typeof code !== "string" || code.trim().length === 0) {
      throw new Error("policy.retryableCodes must contain only non-blank strings");
    }
  }
  if (new Set(value).size !== value.length) {
    throw new Error("policy.retryableCodes must not contain duplicates");
  }
  return [...value];
}
function normalizePolicy(value) {
  if (value === void 0) {
    return {
      mode: MODE_NORMAL,
      maxRetries: DEFAULT_POLICY.maxRetries,
      retryableCodes: [...DEFAULT_POLICY.retryableCodes],
      backoff: { ...DEFAULT_BACKOFF }
    };
  }
  if (!isPlainObject(value)) throw new Error("policy must be an object or undefined");
  const mode = value.mode;
  if (mode !== MODE_NORMAL && mode !== MODE_ALWAYS) {
    throw new Error('policy.mode must be "normal" or "always"');
  }
  if (mode === MODE_ALWAYS) {
    assertKnownKeys(value, ALWAYS_KEYS, "policy");
    return { mode, backoff: resolveBackoff(value.backoff, "policy.backoff") };
  }
  assertKnownKeys(value, NORMAL_KEYS, "policy");
  const maxRetries = value.maxRetries ?? NORMAL_POLICY_FIELDS.maxRetries;
  if (!Number.isSafeInteger(maxRetries) || maxRetries < 0) {
    throw new Error("policy.maxRetries must be a non-negative safe integer");
  }
  const retryableCodes = value.retryableCodes === void 0 ? [...DEFAULT_POLICY.retryableCodes] : resolveRetryableCodes(value.retryableCodes);
  return {
    mode,
    maxRetries,
    retryableCodes,
    backoff: resolveBackoff(value.backoff, "policy.backoff")
  };
}
function getPath(value, path) {
  let current = value;
  for (const key of path) {
    if (current === null || typeof current !== "object") return void 0;
    if (!Object.prototype.hasOwnProperty.call(current, key)) return void 0;
    current = current[key];
  }
  return current;
}
function indexNamespaces(namespaces) {
  const byNamespace = /* @__PURE__ */ new Map();
  if (namespaces === void 0 || namespaces === null) return byNamespace;
  const views = namespaces instanceof Map ? [...namespaces.values()] : Array.isArray(namespaces) ? namespaces : Object.values(namespaces);
  for (const view of views) {
    if (isPlainObject(view) && typeof view.ns === "string") byNamespace.set(view.ns, view);
  }
  return byNamespace;
}
function resolveRef(root, node) {
  let current = node;
  const seen = /* @__PURE__ */ new Set();
  while (isPlainObject(current) && typeof current.$ref === "string") {
    const ref = current.$ref;
    if (!ref.startsWith("#/") || seen.has(ref)) return void 0;
    seen.add(ref);
    current = getPath(root, ref.slice(2).split("/"));
  }
  return current;
}
function isObjectTyped(node) {
  return node.type === "object" || Array.isArray(node.type) && node.type.includes("object");
}
function objectBranch(root, node, depth = 0) {
  if (depth > 16) return void 0;
  const resolved = resolveRef(root, node);
  if (!isPlainObject(resolved) || Array.isArray(resolved)) return void 0;
  if (isPlainObject(resolved.properties) || isPlainObject(resolved.additionalProperties) || isObjectTyped(resolved)) {
    return resolved;
  }
  for (const key of ["anyOf", "oneOf"]) {
    if (Array.isArray(resolved[key])) {
      for (const branch of resolved[key]) {
        const candidate = objectBranch(root, branch, depth + 1);
        if (candidate !== void 0) return candidate;
      }
      return void 0;
    }
  }
  return void 0;
}
function hasOwn(object, key) {
  return isPlainObject(object) && Object.prototype.hasOwnProperty.call(object, key);
}
function isWireSchema(schema) {
  return isPlainObject(schema) && typeof schema.uid === "number" && isPlainObject(schema.refs);
}
function wireNode(root, node) {
  let current = node;
  const seen = /* @__PURE__ */ new Set();
  while (typeof current === "number") {
    if (seen.has(current)) return void 0;
    seen.add(current);
    current = root.refs[current];
  }
  return isPlainObject(current) ? current : void 0;
}
function wireStep(root, node, segment) {
  const resolved = wireNode(root, node);
  if (resolved === void 0) return void 0;
  switch (resolved.type) {
    case "object":
      return isPlainObject(resolved.dict) ? resolved.dict[segment] : void 0;
    case "dict":
      return resolved.inner;
    case "lazy":
    case "transform":
      return resolved.inner;
    case "union":
    case "intersect": {
      for (const branch of Array.isArray(resolved.list) ? resolved.list : []) {
        const next = wireStep(root, branch, segment);
        if (next !== void 0) return next;
      }
      return void 0;
    }
    default:
      return void 0;
  }
}
function wireDeclaresField(root, node, field) {
  const resolved = wireNode(root, node);
  if (resolved === void 0) return false;
  switch (resolved.type) {
    case "object":
      return isPlainObject(resolved.dict) && Object.prototype.hasOwnProperty.call(resolved.dict, field);
    case "union":
    case "intersect":
      return (Array.isArray(resolved.list) ? resolved.list : []).some((branch) => wireDeclaresField(root, branch, field));
    case "lazy":
    case "transform":
      return wireDeclaresField(root, resolved.inner, field);
    default:
      return false;
  }
}
function wireSchemaSupportsField(schema, settingsPath, field) {
  let node = schema.uid;
  for (const segment of settingsPath) {
    node = wireStep(schema, node, segment);
    if (node === void 0) return false;
  }
  return wireDeclaresField(schema, node, field);
}
function schemaSupportsField(schema, settingsPath, field) {
  if (isWireSchema(schema)) return wireSchemaSupportsField(schema, settingsPath, field);
  let node = objectBranch(schema, schema);
  for (const segment of settingsPath) {
    if (node === void 0) return false;
    const properties = isPlainObject(node.properties) ? node.properties : void 0;
    let next = properties !== void 0 && Object.prototype.hasOwnProperty.call(properties, segment) ? properties[segment] : void 0;
    if (next === void 0) {
      const additional = objectBranch(schema, node.additionalProperties);
      if (additional === void 0) return false;
      next = hasOwn(additional.properties, segment) ? additional.properties[segment] : additional;
    }
    node = objectBranch(schema, next);
  }
  return node !== void 0 && hasOwn(node.properties, field);
}
function pathLabel(settingsPath) {
  return settingsPath.length === 0 ? "the section root" : `"${settingsPath.join(".")}"`;
}
function buildRow(provider, displayName, ns, settingsPath, view) {
  const row = {
    provider,
    displayName: typeof displayName === "string" && displayName.length > 0 ? displayName : provider,
    ns,
    settingsPath,
    revision: Number.isSafeInteger(view.revision) ? view.revision : 0,
    policy: normalizePolicy(void 0),
    overridden: getPath(view.user, [...settingsPath, "retryPolicy"]) !== void 0,
    editable: true
  };
  if (!schemaSupportsField(view.schema, settingsPath, "retryPolicy")) {
    row.editable = false;
    row.reason = `provider "${provider}" declares no native retryPolicy at ${pathLabel(settingsPath)}`;
    return row;
  }
  try {
    row.policy = normalizePolicy(getPath(view.value, [...settingsPath, "retryPolicy"]));
  } catch (error) {
    row.editable = false;
    row.reason = `provider "${provider}" stores an invalid retryPolicy: ${error instanceof Error ? error.message : String(error)}`;
  }
  return row;
}
function buildProviderRows(directory, namespaces) {
  const byNamespace = indexNamespaces(namespaces);
  const rows = [];
  if (!Array.isArray(directory)) return rows;
  for (const entry of directory) {
    if (!isPlainObject(entry)) continue;
    const provider = entry.provider;
    if (typeof provider !== "string" || provider.length === 0) continue;
    const ns = entry.settingsNs;
    if (typeof ns !== "string" || ns.length === 0) continue;
    const view = byNamespace.get(ns);
    if (view === void 0) continue;
    const settingsPath = Array.isArray(entry.settingsPath) ? [...entry.settingsPath] : [];
    const configured = settingsPath.length === 0 || getPath(view.value, settingsPath) !== void 0;
    if (!configured) continue;
    rows.push(buildRow(provider, entry.displayName, ns, settingsPath, view));
  }
  return rows;
}
var GLOBAL_SETTINGS_NS = "dsh-retry-settings";
function isSamePolicy(left, right) {
  if (left.mode !== right.mode) return false;
  if (left.mode === "normal") {
    if (left.maxRetries !== right.maxRetries) return false;
    const leftCodes = [...left.retryableCodes].sort();
    const rightCodes = [...right.retryableCodes].sort();
    if (leftCodes.length !== rightCodes.length) return false;
    for (let index = 0; index < leftCodes.length; index += 1) {
      if (leftCodes[index] !== rightCodes[index]) return false;
    }
  }
  return left.backoff.initialDelayMs === right.backoff.initialDelayMs && left.backoff.maxDelayMs === right.backoff.maxDelayMs && left.backoff.jitterRatio === right.backoff.jitterRatio;
}
function policyReason(error) {
  return error instanceof Error ? error.message : String(error);
}
function hasProviderOverride(overrides, provider) {
  return isPlainObject(overrides) && Object.prototype.hasOwnProperty.call(overrides, provider);
}
function effectivePolicyFor(policy, overrides, provider) {
  return hasProviderOverride(overrides, provider) ? overrides[provider] : policy;
}
function summarizeProviderSync(policy, rows, overrides) {
  const list = Array.isArray(rows) ? rows : [];
  const summary = { total: list.length, synced: 0, pending: [] };
  if (list.length === 0) return summary;
  for (const row of list) {
    if (row.editable !== true) {
      summary.pending.push({ provider: row.provider, reason: row.reason ?? "this provider cannot hold a retry policy" });
      continue;
    }
    const overridden = hasProviderOverride(overrides, row.provider);
    const desiredRaw = overridden ? overrides[row.provider] : policy;
    if (desiredRaw === void 0 || desiredRaw === null) {
      summary.pending.push({
        provider: row.provider,
        reason: overridden ? "the provider override is not configured" : "no global policy is configured"
      });
      continue;
    }
    let desired;
    try {
      desired = normalizePolicy(desiredRaw);
    } catch (error) {
      summary.pending.push({
        provider: row.provider,
        reason: overridden ? `the desired policy for provider "${row.provider}" is invalid: ${policyReason(error)}` : `the global policy is invalid: ${policyReason(error)}`
      });
      continue;
    }
    let current;
    try {
      current = normalizePolicy(row.policy);
    } catch (error) {
      summary.pending.push({ provider: row.provider, reason: `the provider policy is invalid: ${policyReason(error)}` });
      continue;
    }
    if (isSamePolicy(current, desired)) summary.synced += 1;
    else summary.pending.push({
      provider: row.provider,
      reason: overridden ? "the provider policy differs from its configured override" : "the provider policy differs from the global policy"
    });
  }
  return summary;
}

// src/ui-draft.js
var GLOBAL_POLICY_PATH = ["policy"];
var VALIDATED_FIELDS = ["maxRetries", "initialDelayMs", "maxDelayMs", "jitterPercent", "retryableCodes"];
function globalSetOperation(policy) {
  return { op: "set", path: [...GLOBAL_POLICY_PATH], value: normalizePolicy(policy) };
}
function globalResetOperation() {
  return { op: "unset", path: [...GLOBAL_POLICY_PATH] };
}
function providerPolicyPath(provider) {
  return ["providers", provider];
}
function providerSetOperation(provider, policy) {
  return { op: "set", path: providerPolicyPath(provider), value: normalizePolicy(policy) };
}
function providerResetOperation(provider) {
  return { op: "unset", path: providerPolicyPath(provider) };
}
function draftFromPolicy(policy) {
  const resolved = normalizePolicy(policy);
  return {
    mode: resolved.mode,
    maxRetries: resolved.mode === "always" ? DEFAULT_POLICY.maxRetries : resolved.maxRetries,
    initialDelayMs: resolved.backoff.initialDelayMs,
    maxDelayMs: resolved.backoff.maxDelayMs,
    jitterPercent: resolved.backoff.jitterRatio * 100,
    retryableCodes: [...resolved.mode === "always" ? DEFAULT_POLICY.retryableCodes : resolved.retryableCodes]
  };
}
function requireNumber(value, label) {
  if (value === null || value === void 0 || typeof value === "string" && value.trim() === "") {
    throw new Error(`${label} is required`);
  }
  const resolved = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(resolved)) throw new Error(`${label} must be a number`);
  return resolved;
}
function policyFromDraft(draft) {
  const backoff = {
    initialDelayMs: requireNumber(draft.initialDelayMs, "policy.backoff.initialDelayMs"),
    maxDelayMs: requireNumber(draft.maxDelayMs, "policy.backoff.maxDelayMs"),
    jitterRatio: requireNumber(draft.jitterPercent, "policy.backoff.jitterPercent") / 100
  };
  if (draft.mode === "always") return { mode: "always", backoff };
  return {
    mode: "normal",
    maxRetries: requireNumber(draft.maxRetries, "policy.maxRetries"),
    retryableCodes: [...draft.retryableCodes],
    backoff
  };
}
function draftFieldErrors(draft) {
  if (draft === null || draft === void 0) return {};
  try {
    normalizePolicy(policyFromDraft(draft));
    return {};
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const field = VALIDATED_FIELDS.find((name) => message.includes(name)) ?? "form";
    return { [field]: message };
  }
}
function draftIsDirty(draft, policy) {
  return JSON.stringify(draftFromPolicy(policy)) !== JSON.stringify(draft ?? draftFromPolicy(policy));
}

// src/ui-controller.js
var POLICY_PATH = ["policy"];
var EMPTY_STATE = Object.freeze({
  status: "loading",
  error: null,
  notice: null,
  available: false,
  writable: true,
  configured: false,
  overridden: false,
  saving: false,
  dirty: false,
  failed: false,
  revision: null,
  fieldErrors: {},
  sync: { total: 0, synced: 0, pending: [] },
  defaultCodes: Object.freeze([...DEFAULT_POLICY.retryableCodes]),
  draft: null,
  providers: [],
  selectedProvider: null,
  providerDraft: null,
  providerFieldErrors: {},
  providerDirty: false,
  providerConfigured: false,
  savingScope: "global"
});
function messageOf(error) {
  return error instanceof Error ? error.message : String(error);
}
function createRetrySettingsController({ remote }) {
  let state = { ...EMPTY_STATE };
  let namespace = null;
  let providerRows = [];
  let baselineRevision = null;
  let providerBaseline = null;
  let generation = 0;
  let pendingRefresh = false;
  let disposed = false;
  const listeners = /* @__PURE__ */ new Set();
  const store = {
    getSnapshot: () => state,
    subscribe(listener) {
      listeners.add(listener);
      return () => listeners.delete(listener);
    }
  };
  function publish(patch) {
    if (disposed) return;
    state = { ...state, ...patch };
    for (const listener of [...listeners]) listener();
  }
  function invalidateReads() {
    generation += 1;
  }
  function runDeferredRefresh() {
    if (!pendingRefresh || disposed) return;
    pendingRefresh = false;
    void refresh();
  }
  function effectivePolicy() {
    return namespace === null ? void 0 : getPath(namespace.value, POLICY_PATH);
  }
  function overrideMap() {
    const value = namespace === null ? void 0 : getPath(namespace.value, ["providers"]);
    return value === null || value === void 0 ? {} : value;
  }
  function desiredForProvider(provider) {
    return effectivePolicyFor(effectivePolicy(), overrideMap(), provider);
  }
  function buildProviders() {
    const global = effectivePolicy();
    const overrides = overrideMap();
    return providerRows.map((row) => {
      const desired = effectivePolicyFor(global, overrides, row.provider);
      const one = summarizeProviderSync(desired, [row]);
      return {
        provider: row.provider,
        displayName: row.displayName,
        editable: row.editable === true,
        hasOverride: hasProviderOverride(overrides, row.provider),
        synced: one.synced === 1,
        reason: one.pending[0]?.reason ?? null,
        policy: desired === void 0 || desired === null ? null : normalizePolicyForView(desired)
      };
    });
  }
  function normalizePolicyForView(policy) {
    try {
      return draftFromPolicy(policy);
    } catch {
      return draftFromPolicy(DEFAULT_POLICY);
    }
  }
  async function read() {
    const mine = ++generation;
    let directory;
    let describe;
    try {
      [directory, describe] = await Promise.all([
        remote.llm.listConfigurableProviders(),
        remote.settings.describe()
      ]);
    } catch (error) {
      if (disposed || mine !== generation) return { stale: true };
      return { failure: messageOf(error) };
    }
    if (disposed || mine !== generation) return { stale: true };
    if (!directory.ok) return { failure: directory.error.message };
    if (!describe.ok) return { failure: describe.error.message };
    const namespaces = describe.value.namespaces ?? [];
    return {
      view: namespaces.find((candidate) => candidate.ns === GLOBAL_SETTINGS_NS) ?? null,
      rows: buildProviderRows(directory.value, namespaces),
      writable: describe.value.writable !== false
    };
  }
  function adopt(result, { draftOverride, keepBaseline = false } = {}) {
    providerRows = result.rows;
    namespace = result.view;
    const effective = effectivePolicy();
    const configured = effective !== void 0;
    const revision = namespace === null || !Number.isSafeInteger(namespace.revision) ? null : namespace.revision;
    if (!keepBaseline) baselineRevision = revision;
    const draft = namespace === null ? null : draftOverride ?? draftFromPolicy(effective);
    const selectedStillExists = state.selectedProvider === null || providerRows.some((row) => row.provider === state.selectedProvider);
    publish({
      status: "ready",
      error: null,
      available: namespace !== null,
      writable: result.writable,
      configured,
      overridden: namespace !== null && getPath(namespace.user, POLICY_PATH) !== void 0,
      revision: baselineRevision,
      draft,
      fieldErrors: draft === null ? {} : draftFieldErrors(draft),
      dirty: draft === null ? false : draftIsDirty(draft, effective),
      sync: summarizeProviderSync(effective, providerRows, overrideMap()),
      providers: buildProviders(),
      failed: false,
      notice: namespace === null ? { kind: "unavailable" } : configured ? null : { kind: "unconfigured" },
      ...selectedStillExists ? {} : {
        selectedProvider: null,
        providerDraft: null,
        providerFieldErrors: {},
        providerDirty: false,
        providerConfigured: false
      }
    });
  }
  function adoptWrittenView(view) {
    namespace = view;
    const effective = effectivePolicy();
    baselineRevision = Number.isSafeInteger(view.revision) ? view.revision : baselineRevision;
    publish({
      available: true,
      configured: effective !== void 0,
      overridden: getPath(view.user, POLICY_PATH) !== void 0,
      revision: baselineRevision,
      draft: draftFromPolicy(effective),
      fieldErrors: {},
      dirty: false,
      sync: summarizeProviderSync(effective, providerRows, overrideMap()),
      providers: buildProviders()
    });
  }
  async function load() {
    const result = await read();
    if (result.stale === true) return;
    if (result.failure !== void 0) {
      publish({
        status: "unavailable",
        error: result.failure,
        available: false,
        draft: null,
        revision: null,
        notice: { kind: "unavailable" }
      });
      return;
    }
    adopt(result);
  }
  async function refresh() {
    if (disposed) return;
    if (state.saving) {
      pendingRefresh = true;
      return;
    }
    const previousRevision = state.revision;
    const previousPolicy = JSON.stringify(effectivePolicy() ?? null);
    const previousOverrides = JSON.stringify(overrideMap() ?? {});
    const result = await read();
    if (result.stale === true) return;
    if (result.failure !== void 0) {
      publish({ error: result.failure });
      return;
    }
    const keepDraft = state.dirty === true && namespace !== null;
    const keepProviderDraft = state.providerDirty === true && state.selectedProvider !== null && namespace !== null;
    const nextPolicy = result.view === null ? void 0 : getPath(result.view.value, POLICY_PATH);
    const nextOverrides = result.view === null ? void 0 : getPath(result.view.value, ["providers"]);
    const changed = previousRevision !== (result.view?.revision ?? null) || previousPolicy !== JSON.stringify(nextPolicy ?? null) || previousOverrides !== JSON.stringify(nextOverrides ?? {});
    adopt(result, { draftOverride: keepDraft ? state.draft : void 0, keepBaseline: keepDraft });
    if (keepDraft && changed) publish({ notice: { kind: "external" } });
    else if (keepProviderDraft && changed) publish({ notice: { kind: "external" } });
  }
  async function write(operations, scope = "global") {
    if (disposed || state.saving || state.available !== true || state.writable !== true) return;
    if (baselineRevision === null || !Number.isSafeInteger(baselineRevision)) return;
    publish({ saving: true, savingScope: scope, notice: null });
    let response;
    try {
      response = await remote.settings.mutate(GLOBAL_SETTINGS_NS, operations, baselineRevision);
    } catch (error) {
      publish({ saving: false, failed: true, notice: { kind: "error", message: messageOf(error) } });
      runDeferredRefresh();
      return;
    }
    if (disposed) return;
    if (!response.ok) {
      publish({
        saving: false,
        failed: true,
        notice: {
          kind: response.error.code === "settings/conflict" ? "conflict" : "rejected",
          message: response.error.message
        }
      });
      runDeferredRefresh();
      return;
    }
    invalidateReads();
    adoptWrittenView(response.value);
    if (scope === "global") {
      publish({ saving: false, savingScope: "global", failed: false, notice: { kind: "saved" } });
    } else {
      const provider = scope.provider;
      const overrides = overrideMap();
      const configured = hasProviderOverride(overrides, provider);
      const desired = desiredForProvider(provider);
      const draft = desired === void 0 || desired === null ? null : draftFromPolicy(desired);
      providerBaseline = desired;
      publish({
        saving: false,
        savingScope: "global",
        failed: false,
        notice: { kind: "saved" },
        providerDraft: draft,
        providerFieldErrors: draft === null ? {} : draftFieldErrors(draft),
        providerDirty: false,
        providerConfigured: configured
      });
    }
    runDeferredRefresh();
  }
  function editDraft(mutate) {
    if (disposed || state.saving || state.draft === null || state.selectedProvider !== null) return;
    const draft = mutate(state.draft);
    publish({
      draft,
      fieldErrors: draftFieldErrors(draft),
      dirty: draftIsDirty(draft, effectivePolicy()),
      failed: false,
      notice: null
    });
  }
  const actions = {
    setField(field, value) {
      editDraft((draft) => ({ ...draft, [field]: value }));
    },
    toggleCode(code, checked) {
      editDraft((draft) => ({ ...draft, retryableCodes: nextCodes(draft.retryableCodes, code, checked) }));
    },
    addCustomCode(code) {
      const value = String(code).trim();
      if (value === "") return;
      editDraft((draft) => ({ ...draft, retryableCodes: nextCodes(draft.retryableCodes, value, true) }));
    },
    removeCustomCode(code) {
      editDraft((draft) => ({ ...draft, retryableCodes: nextCodes(draft.retryableCodes, code, false) }));
    },
    discard() {
      if (disposed || state.saving || state.draft === null || state.selectedProvider !== null) return;
      invalidateReads();
      baselineRevision = Number.isSafeInteger(namespace?.revision) ? namespace.revision : null;
      publish({
        revision: baselineRevision,
        draft: draftFromPolicy(effectivePolicy()),
        fieldErrors: {},
        dirty: false,
        failed: false,
        notice: null
      });
    },
    async save() {
      if (disposed || state.saving || state.draft === null || state.selectedProvider !== null) return;
      const fieldErrors = draftFieldErrors(state.draft);
      if (Object.keys(fieldErrors).length > 0) {
        publish({ fieldErrors, notice: { kind: "invalid", message: Object.values(fieldErrors)[0] } });
        return;
      }
      let operations;
      try {
        operations = [globalSetOperation(policyFromDraft(state.draft))];
      } catch (error) {
        publish({ notice: { kind: "invalid", message: messageOf(error) } });
        return;
      }
      await write(operations);
    },
    async restoreInherited() {
      if (disposed || state.saving || state.overridden !== true || state.selectedProvider !== null) return;
      await write([globalResetOperation()]);
    },
    selectProvider(provider) {
      if (disposed || state.saving || state.dirty === true || state.available !== true) return;
      const row = providerRows.find((candidate) => candidate.provider === provider);
      if (row === void 0) return;
      const hasOverride = hasProviderOverride(overrideMap(), provider);
      const desired = desiredForProvider(provider);
      const draft = desired === void 0 || desired === null ? draftFromPolicy(DEFAULT_POLICY) : draftFromPolicy(desired);
      providerBaseline = desired;
      publish({
        selectedProvider: provider,
        providerDraft: draft,
        providerFieldErrors: draftFieldErrors(draft),
        providerDirty: false,
        providerConfigured: hasOverride,
        notice: null
      });
    },
    closeProviderEditor() {
      if (disposed || state.saving || state.providerDirty === true) return;
      publish({
        selectedProvider: null,
        providerDraft: null,
        providerFieldErrors: {},
        providerDirty: false,
        providerConfigured: false
      });
      providerBaseline = null;
    },
    setProviderField(field, value) {
      if (disposed || state.saving || state.providerDraft === null || state.selectedProvider === null) return;
      const draft = { ...state.providerDraft, [field]: value };
      publish({
        providerDraft: draft,
        providerFieldErrors: draftFieldErrors(draft),
        providerDirty: draftIsDirty(draft, providerBaseline),
        failed: false,
        notice: null
      });
    },
    toggleProviderCode(code, checked) {
      if (disposed || state.saving || state.providerDraft === null || state.selectedProvider === null) return;
      const draft = { ...state.providerDraft, retryableCodes: nextCodes(state.providerDraft.retryableCodes, code, checked) };
      publish({
        providerDraft: draft,
        providerFieldErrors: draftFieldErrors(draft),
        providerDirty: draftIsDirty(draft, providerBaseline),
        failed: false,
        notice: null
      });
    },
    addProviderCustomCode(code) {
      if (disposed || state.saving || state.providerDraft === null || state.selectedProvider === null) return;
      const value = String(code).trim();
      if (value === "") return;
      const draft = { ...state.providerDraft, retryableCodes: nextCodes(state.providerDraft.retryableCodes, value, true) };
      publish({
        providerDraft: draft,
        providerFieldErrors: draftFieldErrors(draft),
        providerDirty: draftIsDirty(draft, providerBaseline),
        failed: false,
        notice: null
      });
    },
    removeProviderCustomCode(code) {
      if (disposed || state.saving || state.providerDraft === null || state.selectedProvider === null) return;
      const draft = { ...state.providerDraft, retryableCodes: nextCodes(state.providerDraft.retryableCodes, code, false) };
      publish({
        providerDraft: draft,
        providerFieldErrors: draftFieldErrors(draft),
        providerDirty: draftIsDirty(draft, providerBaseline),
        failed: false,
        notice: null
      });
    },
    discardProviderDraft() {
      if (disposed || state.saving || state.selectedProvider === null) return;
      if (state.providerConfigured === true) {
        const desired = desiredForProvider(state.selectedProvider);
        const draft = desired === void 0 || desired === null ? draftFromPolicy(DEFAULT_POLICY) : draftFromPolicy(desired);
        providerBaseline = desired;
        publish({
          providerDraft: draft,
          providerFieldErrors: draftFieldErrors(draft),
          providerDirty: false,
          failed: false,
          notice: null
        });
        return;
      }
      actions.closeProviderEditor();
    },
    async saveProviderOverride() {
      if (disposed || state.saving || state.providerDraft === null || state.selectedProvider === null) return;
      const fieldErrors = draftFieldErrors(state.providerDraft);
      if (Object.keys(fieldErrors).length > 0) {
        publish({ providerFieldErrors: fieldErrors, notice: { kind: "invalid", message: Object.values(fieldErrors)[0] } });
        return;
      }
      let operations;
      try {
        operations = [providerSetOperation(state.selectedProvider, policyFromDraft(state.providerDraft))];
      } catch (error) {
        publish({ notice: { kind: "invalid", message: messageOf(error) } });
        return;
      }
      await write(operations, { scope: "provider", provider: state.selectedProvider });
    },
    async restoreProviderInherited() {
      if (disposed || state.saving || state.selectedProvider === null || state.providerConfigured !== true) return;
      await write([providerResetOperation(state.selectedProvider)], { scope: "provider", provider: state.selectedProvider });
    }
  };
  return {
    store,
    load,
    refresh,
    actions,
    dispose() {
      disposed = true;
      generation += 1;
      pendingRefresh = false;
      baselineRevision = null;
      namespace = null;
      providerRows = [];
      providerBaseline = null;
      listeners.clear();
      state = { ...EMPTY_STATE };
    }
  };
}
function nextCodes(codes, code, checked) {
  if (checked === true) return codes.includes(code) ? codes : [...codes, code];
  return codes.filter((candidate) => candidate !== code);
}

// src/ui-view.js
var import_react = __toESM(require("react"), 1);
var h = import_react.default.createElement;
var NUMERIC_FIELDS = [
  ["maxRetries", "maxRetriesHint", "unitRetries"],
  ["initialDelayMs", null, "unitMilliseconds"],
  ["maxDelayMs", null, "unitMilliseconds"],
  ["jitterPercent", null, "unitPercent"]
];
var MODES = [
  ["normal", "modeNormal"],
  ["always", "modeAlways"]
];
function parseNumeric(raw) {
  return raw.trim() === "" ? null : Number(raw);
}
function noticeTone(kind) {
  switch (kind) {
    case "saved":
      return "success";
    case "unconfigured":
      return "info";
    case "external":
    case "conflict":
      return "warning";
    default:
      return "danger";
  }
}
function draftSummary(draft) {
  if (draft === null || draft === void 0) return "";
  if (draft.mode === "always") return "always \xB7 backoff";
  return `normal \xB7 ${draft.maxRetries} retries`;
}
function RetrySettingsView({ snapshot, actions, t }) {
  const [customCode, setCustomCode] = import_react.default.useState("");
  const [providerCustomCode, setProviderCustomCode] = import_react.default.useState("");
  const header = [
    h(
      "div",
      { key: "heading", className: "drs-titleRow" },
      h("h2", { key: "title", className: "drs-title" }, t("nav")),
      h("span", { key: "global", className: "drs-tag", "data-tone": "outline" }, t("globalBadge"))
    ),
    h("p", { key: "intro", className: "drs-intro" }, t("intro"))
  ];
  const statusLine = (key, text) => h("p", { key, className: "drs-unavailable", role: "status" }, text);
  if (snapshot.status === "loading") {
    return h("section", { className: "drs-section" }, [...header, statusLine("loading", t("loading"))]);
  }
  if (snapshot.available !== true) {
    return h(
      "section",
      { className: "drs-section" },
      [...header, statusLine("unavailable", snapshot.notice?.message ?? t("unavailable"))]
    );
  }
  const selectedProvider = snapshot.selectedProvider ?? null;
  const draft = snapshot.draft;
  const fieldErrors = snapshot.fieldErrors ?? {};
  const invalid = Object.keys(fieldErrors).length > 0;
  const globalLocked = draft === null || snapshot.writable !== true || snapshot.saving === true || selectedProvider !== null;
  const blocked = snapshot.saving === true || snapshot.dirty !== true && snapshot.configured === true || invalid || snapshot.writable !== true || selectedProvider !== null;
  const defaultCodes = snapshot.defaultCodes ?? [];
  const customCodes = (draft?.retryableCodes ?? []).filter((code) => !defaultCodes.includes(code));
  const sync = snapshot.sync;
  const pending = sync === null || sync === void 0 ? [] : sync.pending;
  const total = sync?.total ?? 0;
  const synced = sync?.synced ?? 0;
  const syncState = total === 0 ? "idle" : pending.length === 0 ? "done" : "warning";
  const notice = snapshot.notice;
  const noticeText = notice === null || notice === void 0 ? null : notice.message ?? t(notice.kind === "external" ? "externalChanged" : notice.kind);
  const noticeQuiet = notice?.kind === "saved" || notice?.kind === "unconfigured";
  const syncReason = (reason) => reason === "the provider policy differs from the global policy" ? t("syncDiffers") : reason;
  const numericField = ({ field, hintKey, unitKey, value, error, locked, onChange, idPrefix }) => h(
    "div",
    { className: "drs-field", key: field },
    h("label", { className: "drs-label", htmlFor: `${idPrefix}-${field}` }, t(field)),
    h(
      "div",
      { className: "drs-inputShell", "data-invalid": error === void 0 ? "false" : "true" },
      h("input", {
        id: `${idPrefix}-${field}`,
        className: "drs-input",
        type: "text",
        inputMode: "numeric",
        ...error === void 0 ? {} : { "aria-invalid": true },
        value: value ?? "",
        disabled: locked,
        onChange: (event) => onChange(field, parseNumeric(event.target.value))
      }),
      h("span", { className: "drs-inputUnit" }, t(unitKey))
    ),
    error === void 0 ? hintKey === null ? null : h("p", { className: "drs-hint" }, t(hintKey)) : h("p", { className: "drs-invalid" }, error)
  );
  const segmentControl = ({ draft: draft2, locked, onChange }) => {
    const segmentIndex = Math.max(0, MODES.findIndex(([value]) => value === draft2.mode));
    return h(
      "div",
      {
        role: "tablist",
        "aria-label": t("mode"),
        className: "drs-segmented",
        style: { "--drs-segment-count": String(MODES.length), "--drs-segment-index": String(segmentIndex) }
      },
      h("span", { "aria-hidden": "true", className: "drs-segmentedIndicator" }),
      MODES.map(([value, labelKey]) => h(
        "button",
        {
          key: value,
          type: "button",
          role: "tab",
          className: "drs-segment",
          "aria-selected": draft2.mode === value,
          tabIndex: draft2.mode === value ? 0 : -1,
          disabled: locked,
          onClick: () => onChange("mode", value)
        },
        t(labelKey)
      ))
    );
  };
  const codesEditor = ({ draft: draft2, locked, onToggle, onAdd, onRemove, custom, setCustom, idPrefix }) => {
    const codes = draft2.retryableCodes ?? [];
    const extras = codes.filter((code) => !defaultCodes.includes(code));
    return [
      h("p", { key: "policyHint", className: "drs-hint" }, t("policyHint")),
      h(
        "div",
        { key: "chips", role: "group", "aria-label": t("retryableCodes"), className: "drs-chipList" },
        defaultCodes.map((code) => h(
          "label",
          { key: code, className: "drs-chip", "data-checked": String(codes.includes(code)) },
          h("input", {
            type: "checkbox",
            value: code,
            checked: codes.includes(code),
            disabled: locked,
            onChange: (event) => onToggle(code, event.target.checked)
          }),
          h("span", null, code)
        )),
        extras.map((code) => h(
          "span",
          { key: code, className: "drs-chip drs-chipCustom" },
          code,
          h(
            "button",
            {
              type: "button",
              className: "drs-chipRemove",
              "aria-label": `${t("removeCode")} ${code}`,
              disabled: locked,
              onClick: () => onRemove(code)
            },
            "\xD7"
          )
        ))
      ),
      h("span", { key: "customLabel", className: "drs-label" }, t("codeCustom")),
      h(
        "div",
        { key: "addRow", className: "drs-addRow" },
        h(
          "div",
          { className: "drs-inputShell" },
          h("input", {
            className: "drs-input",
            type: "text",
            "aria-label": t("customCode"),
            placeholder: t("customCodePlaceholder"),
            value: custom,
            disabled: locked,
            onChange: (event) => setCustom(event.target.value)
          })
        ),
        h(
          "button",
          {
            type: "button",
            className: "drs-secondaryButton",
            disabled: locked || custom.trim() === "",
            onClick: () => {
              const value = custom.trim();
              if (value === "") return;
              onAdd(value);
              setCustom("");
            }
          },
          t("add")
        )
      )
    ];
  };
  const policyEditor = ({ draft: draft2, fieldErrors: fieldErrors2, locked, onSetField, onToggleCode, onAddCode, onRemoveCode, custom, setCustom, idPrefix }) => {
    const fields = draft2.mode === "normal" ? NUMERIC_FIELDS : NUMERIC_FIELDS.filter(([field]) => field !== "maxRetries");
    return h(
      "div",
      { className: "drs-panel" },
      h(
        "div",
        { key: "mode", className: "drs-panelSection" },
        h(
          "div",
          { className: "drs-head" },
          h("div", { className: "drs-labelGroup" }, h("h3", { className: "drs-panelTitle" }, t("mode")))
        ),
        segmentControl({ draft: draft2, locked, onChange: onSetField }),
        draft2.mode === "always" ? h("p", { className: "drs-hint" }, t("alwaysNote")) : null
      ),
      h(
        "div",
        { key: "parameters", className: "drs-panelSection" },
        h(
          "div",
          { className: "drs-head" },
          h("div", { className: "drs-labelGroup" }, h("h3", { className: "drs-panelTitle" }, t("parametersTitle")))
        ),
        h(
          "div",
          { className: "drs-numberGrid" },
          fields.map(([field, hintKey, unitKey]) => numericField({
            field,
            hintKey,
            unitKey,
            value: draft2[field],
            error: fieldErrors2[field],
            locked,
            onChange: onSetField,
            idPrefix
          }))
        ),
        h("p", { className: "drs-hint" }, t("backoffHint"))
      ),
      draft2.mode === "normal" ? h(
        "div",
        { key: "codes", className: "drs-panelSection" },
        h(
          "div",
          { className: "drs-head" },
          h("div", { className: "drs-labelGroup" }, h("h3", { className: "drs-panelTitle" }, t("retryableCodes")))
        ),
        ...codesEditor({
          draft: draft2,
          locked,
          onToggle: onToggleCode,
          onAdd: onAddCode,
          onRemove: onRemoveCode,
          custom,
          setCustom,
          idPrefix
        })
      ) : null
    );
  };
  const globalEditor = (selectedProvider2) => policyEditor({
    draft,
    fieldErrors,
    locked: globalLocked,
    onSetField: actions.setField,
    onToggleCode: actions.toggleCode,
    onAddCode: actions.addCustomCode,
    onRemoveCode: actions.removeCustomCode,
    custom: customCode,
    setCustom: setCustomCode,
    idPrefix: "drs"
  });
  const providerRows = snapshot.providers ?? [];
  const provider = providerRows.find((row) => row.provider === selectedProvider) ?? null;
  const providerDraft = snapshot.providerDraft;
  const providerErrors = snapshot.providerFieldErrors ?? {};
  const providerLocked = providerDraft === null || snapshot.writable !== true || snapshot.saving === true;
  const providerBlocked = snapshot.saving === true || snapshot.providerDirty !== true && snapshot.providerConfigured === true || Object.keys(providerErrors).length > 0 || snapshot.writable !== true;
  const children = [
    snapshot.writable === true ? null : h("p", { key: "readonly", className: "drs-readOnly", role: "status" }, t("readOnly")),
    snapshot.error === null || snapshot.error === void 0 ? null : h("p", { key: "error", className: "drs-notice", "data-tone": "danger", role: "alert" }, `${t("readFailed")}${snapshot.error}`),
    noticeText === null ? null : h(
      "p",
      {
        key: "notice",
        className: "drs-notice",
        "data-tone": noticeTone(notice.kind),
        role: noticeQuiet ? "status" : "alert",
        "data-kind": notice.kind
      },
      noticeText
    ),
    h(
      "div",
      { key: "globalSection", className: "drs-globalSection" },
      h(
        "div",
        { className: "drs-head" },
        h(
          "div",
          { className: "drs-labelGroup" },
          h("h3", { className: "drs-panelTitle" }, t("globalTitle")),
          snapshot.configured === true ? h("span", { className: "drs-badges" }, h("span", { className: "drs-tag", "data-tone": "neutral" }, t("overridden"))) : h("span", { className: "drs-badges" }, h("span", { className: "drs-tag", "data-tone": "info" }, t("unconfiguredBadge")))
        ),
        snapshot.configured === true && selectedProvider === null ? h(
          "button",
          {
            type: "button",
            className: "drs-reset",
            disabled: globalLocked,
            onClick: () => actions.restoreInherited()
          },
          t("resetToDefault")
        ) : null
      ),
      globalEditor(selectedProvider)
    ),
    h(
      "div",
      { key: "providers", className: "drs-providersSection" },
      h(
        "div",
        { className: "drs-head" },
        h("div", { className: "drs-labelGroup" }, h("h3", { className: "drs-panelTitle" }, t("providersTitle")))
      ),
      h(
        "div",
        { className: "drs-providerSummary" },
        h("span", { className: "drs-stateDot", "data-state": syncState, "aria-hidden": "true" }),
        h("p", { className: "drs-hint" }, t("syncSummary", { synced, total })),
        pending.length === 0 ? null : h("span", { className: "drs-tag", "data-tone": "warning" }, t("syncPending", { count: pending.length }))
      ),
      pending.length === 0 ? null : h(
        "ul",
        { className: "drs-syncList" },
        pending.map(
          (entry) => h(
            "li",
            { key: entry.provider, className: "drs-syncItem" },
            h("span", { className: "drs-stateDot", "data-state": "warning", "aria-hidden": "true" }),
            h("span", null, h("span", { className: "drs-syncProvider" }, entry.provider), `${t("syncReasonSeparator")}${syncReason(entry.reason)}`)
          )
        )
      ),
      providerRows.length === 0 ? h("p", { className: "drs-hint" }, t("noProviders")) : h(
        "div",
        { className: "drs-providerList" },
        providerRows.map((row) => {
          const selected = selectedProvider === row.provider;
          const syncedState = row.editable === true ? row.synced === true ? "done" : "warning" : "error";
          return h(
            "div",
            { key: row.provider, className: "drs-providerCard" },
            h(
              "div",
              { className: "drs-providerHead" },
              h("span", { className: "drs-stateDot", "data-state": syncedState, "aria-hidden": "true" }),
              h(
                "span",
                { className: "drs-providerName" },
                h("span", { className: "drs-providerDisplayName" }, row.displayName),
                h("span", { className: "drs-providerId" }, row.provider)
              ),
              h(
                "span",
                { className: "drs-badges" },
                h("span", { className: "drs-tag", "data-tone": row.hasOverride === true ? "warning" : "outline" }, row.hasOverride === true ? t("overrideTag") : t("followGlobalTag")),
                h(
                  "button",
                  {
                    type: "button",
                    className: "drs-secondaryButton drs-providerAction",
                    disabled: snapshot.saving === true || snapshot.dirty === true || row.editable !== true,
                    onClick: () => actions.selectProvider(row.provider)
                  },
                  row.hasOverride === true ? t("editOverride") : t("createOverride")
                )
              )
            ),
            h("p", { className: "drs-hint" }, `${t("syncSummaryShort", { provider: row.displayName })} \xB7 ${draftSummary(row.policy)}`),
            selected && provider !== null && providerDraft !== null ? h(
              "div",
              { className: "drs-providerEditor" },
              policyEditor({
                draft: providerDraft,
                fieldErrors: providerErrors,
                locked: providerLocked,
                onSetField: actions.setProviderField,
                onToggleCode: actions.toggleProviderCode,
                onAddCode: actions.addProviderCustomCode,
                onRemoveCode: actions.removeProviderCustomCode,
                custom: providerCustomCode,
                setCustom: setProviderCustomCode,
                idPrefix: `drs-provider-${row.provider}`
              }),
              h(
                "div",
                { className: "drs-footer" },
                h(
                  "button",
                  {
                    type: "button",
                    className: "drs-save",
                    disabled: providerBlocked,
                    onClick: () => actions.saveProviderOverride()
                  },
                  snapshot.saving === true && (snapshot.savingScope ?? "global") === "provider" ? t("saving") : t("saveOverride")
                ),
                h(
                  "button",
                  {
                    type: "button",
                    className: "drs-secondaryButton",
                    disabled: snapshot.saving === true,
                    onClick: () => actions.discardProviderDraft()
                  },
                  snapshot.providerConfigured === true ? t("discard") : t("cancel")
                ),
                row.hasOverride === true ? h(
                  "button",
                  {
                    type: "button",
                    className: "drs-reset",
                    disabled: snapshot.saving === true,
                    onClick: () => actions.restoreProviderInherited()
                  },
                  t("restoreFollowGlobal")
                ) : null,
                snapshot.providerDirty === true && snapshot.saving !== true ? h("span", { className: "drs-dirty" }, t("dirty")) : null
              )
            ) : null
          );
        })
      )
    ),
    selectedProvider === null ? h(
      "div",
      { key: "footer", className: "drs-footer" },
      snapshot.failed === true ? h("p", { className: "drs-failed", role: "status" }, t("saveFailed")) : null,
      h(
        "button",
        { type: "button", className: "drs-save", disabled: blocked, onClick: () => actions.save() },
        snapshot.saving === true && (snapshot.savingScope ?? "global") === "global" ? t("saving") : t("save")
      ),
      h(
        "button",
        {
          type: "button",
          className: "drs-secondaryButton",
          disabled: snapshot.dirty !== true || snapshot.saving === true,
          onClick: () => actions.discard()
        },
        t("discard")
      ),
      snapshot.dirty === true && snapshot.saving !== true ? h("span", { className: "drs-dirty" }, t("dirty")) : null
    ) : null
  ];
  return h("section", { className: "drs-section" }, [...header, h("div", { key: "form", className: "drs-form" }, children)]);
}

// src/ui-locales.js
var zh = {
  nav: "\u8BF7\u6C42\u91CD\u8BD5",
  globalBadge: "\u5168\u5C40\u7B56\u7565",
  globalTitle: "\u5168\u5C40\u9ED8\u8BA4",
  unconfiguredBadge: "\u672A\u914D\u7F6E",
  providersTitle: "\u4F9B\u5E94\u5546\u8986\u76D6",
  noProviders: "\u5F53\u524D\u6CA1\u6709\u53EF\u914D\u7F6E\u7684\u4F9B\u5E94\u5546\u3002",
  overrideTag: "\u81EA\u5B9A\u4E49",
  followGlobalTag: "\u8DDF\u968F\u5168\u5C40",
  editOverride: "\u7F16\u8F91\u8986\u76D6",
  createOverride: "\u5355\u72EC\u8BBE\u7F6E",
  saveOverride: "\u4FDD\u5B58\u8986\u76D6",
  cancel: "\u53D6\u6D88",
  restoreFollowGlobal: "\u6062\u590D\u8DDF\u968F\u5168\u5C40",
  syncSummaryShort: "{provider}",
  intro: "\u8BBE\u7F6E\u4E00\u4EFD\u5168\u5C40\u9ED8\u8BA4\u91CD\u8BD5\u7B56\u7565\uFF1B\u6BCF\u4E2A\u4F9B\u5E94\u5546\u53EF\u4EE5\u8DDF\u968F\u5168\u5C40\uFF0C\u4E5F\u53EF\u4EE5\u5355\u72EC\u8986\u76D6\u3002\u4FDD\u5B58\u540E\u540C\u6B65\u5230\u5404\u4F9B\u5E94\u5546\u7684\u539F\u751F retryPolicy\u3002",
  loading: "\u6B63\u5728\u8BFB\u53D6\u914D\u7F6E\u2026",
  unavailable: "\u8BE5\u63D2\u4EF6\u5F53\u524D\u672A\u52A0\u8F7D\uFF0C\u6682\u65F6\u65E0\u6CD5\u914D\u7F6E\u3002",
  readOnly: "\u672C\u90E8\u7F72\u7684\u8BBE\u7F6E\u4E3A\u53EA\u8BFB\u3002",
  readFailed: "\u8BFB\u53D6\u8BBE\u7F6E\u5931\u8D25\uFF1A",
  saveFailed: "\u672C\u90E8\u7F72\u6CA1\u6709\u63A5\u53D7\u8FD9\u4E9B\u503C\uFF0C\u5DF2\u4FDD\u7559\u4F9B\u4F60\u4FEE\u6539\u3002",
  saving: "\u4FDD\u5B58\u4E2D\u2026",
  save: "\u4FDD\u5B58",
  discard: "\u653E\u5F03\u4FEE\u6539",
  dirty: "\u6709\u672A\u4FDD\u5B58\u7684\u4FEE\u6539",
  unconfigured: "\u5C1A\u672A\u914D\u7F6E\u5168\u5C40\u7B56\u7565\uFF0C\u5F53\u524D\u663E\u793A\u539F\u751F\u9ED8\u8BA4\u503C\u3002",
  saved: "\u5DF2\u4FDD\u5B58\u3002",
  conflict: "\u8BBE\u7F6E\u5DF2\u88AB\u5176\u4ED6\u7A97\u53E3\u6216\u5916\u90E8\u6587\u4EF6\u4FEE\u6539\uFF0C\u672A\u4FDD\u5B58\u3002",
  rejected: "\u4FDD\u5B58\u88AB\u62D2\u7EDD\uFF1A",
  invalid: "\u914D\u7F6E\u65E0\u6548\uFF1A",
  externalChanged: "\u5168\u5C40\u914D\u7F6E\u5DF2\u5728\u5916\u90E8\u4FEE\u6539\uFF1B\u4FDD\u5B58\u4E0D\u4F1A\u8986\u76D6\u5B83\uFF0C\u8BF7\u653E\u5F03\u5E76\u91CD\u65B0\u8BFB\u53D6\u3002",
  mode: "\u91CD\u8BD5\u6A21\u5F0F",
  parametersTitle: "\u91CD\u8BD5\u53C2\u6570",
  modeNormal: "\u6709\u9650\u91CD\u8BD5",
  modeAlways: "\u6301\u7EED\u91CD\u8BD5",
  alwaysNote: "\u6301\u7EED\u91CD\u8BD5\u6CA1\u6709\u6B21\u6570\u4E0A\u9650\uFF0C\u8BA4\u8BC1\u3001\u989D\u5EA6\u7B49\u6C38\u4E45\u5931\u8D25\u4E5F\u4F1A\u4E00\u76F4\u91CD\u8BD5\uFF0C\u76F4\u5230\u6210\u529F\u6216\u53D6\u6D88\uFF0C\u53EF\u80FD\u91CD\u590D\u8BA1\u8D39\u3002",
  overridden: "\u5DF2\u8986\u76D6",
  resetToDefault: "\u6062\u590D\u9ED8\u8BA4",
  maxRetries: "\u6700\u5927\u91CD\u8BD5\u6B21\u6570",
  maxRetriesHint: "\u4E0D\u542B\u9996\u6B21\u8BF7\u6C42\uFF1B0 \u8868\u793A\u5173\u95ED\u666E\u901A\u91CD\u8BD5\u3002",
  unitRetries: "\u6B21",
  unitMilliseconds: "ms",
  unitPercent: "%",
  initialDelayMs: "\u521D\u59CB\u5EF6\u8FDF\uFF08\u6BEB\u79D2\uFF09",
  maxDelayMs: "\u6700\u5927\u5EF6\u8FDF\uFF08\u6BEB\u79D2\uFF09",
  jitterPercent: "\u968F\u673A\u6296\u52A8\uFF08%\uFF09",
  backoffHint: "\u5EF6\u8FDF\u6309\u6307\u6570\u589E\u957F\u5E76\u53E0\u52A0\u6296\u52A8\uFF0C\u4E14\u4E0D\u8D85\u8FC7\u6700\u5927\u5EF6\u8FDF\u3002",
  retryableCodes: "\u53EF\u91CD\u8BD5\u9519\u8BEF",
  codeDefaults: "\u9ED8\u8BA4\u9519\u8BEF\u7801",
  codeCustom: "\u81EA\u5B9A\u4E49\u9519\u8BEF\u7801",
  customCode: "\u81EA\u5B9A\u4E49\u9519\u8BEF\u7801",
  customCodePlaceholder: "\u4F8B\u5982 GATEWAY_BUSY",
  add: "\u6DFB\u52A0",
  removeCode: "\u79FB\u9664\u9519\u8BEF\u7801",
  policyHint: "RATE_LIMIT \u8868\u793A\u4E34\u65F6\u9650\u6D41\uFF1B\u989D\u5EA6\u6216\u4F59\u989D\u8017\u5C3D\u5C5E\u4E8E QUOTA\uFF0C\u9ED8\u8BA4\u4E0D\u4F1A\u91CD\u8BD5\u3002",
  syncTitle: "\u540C\u6B65\u72B6\u6001",
  syncSummary: "\u5DF2\u540C\u6B65 {synced} / {total} \u4E2A\u4F9B\u5E94\u5546",
  syncPending: "\u672A\u540C\u6B65 {count} \u4E2A",
  syncAll: "\u5168\u90E8\u540C\u6B65\u5B8C\u6210",
  syncDiffers: "\u4F9B\u5E94\u5546\u7B56\u7565\u4E0E\u5168\u5C40\u7B56\u7565\u4E0D\u4E00\u81F4",
  syncNone: "\u6682\u65E0\u4F9B\u5E94\u5546",
  syncReasonSeparator: "\uFF1A"
};
var en = {
  nav: "Request retries",
  globalBadge: "Global policy",
  globalTitle: "Global default",
  unconfiguredBadge: "Not configured",
  providersTitle: "Provider overrides",
  noProviders: "No configurable providers yet.",
  overrideTag: "Override",
  followGlobalTag: "Follows global",
  editOverride: "Edit override",
  createOverride: "Set override",
  saveOverride: "Save override",
  cancel: "Cancel",
  restoreFollowGlobal: "Restore follow global",
  syncSummaryShort: "{provider}",
  intro: "Set one global default retry policy. Each provider can follow the default or define its own override; saving synchronizes the effective policy to each provider\u2019s native retryPolicy.",
  loading: "Loading configuration\u2026",
  unavailable: "This plugin is not loaded, so it cannot be configured right now.",
  readOnly: "This deployment stores settings read-only.",
  readFailed: "Reading settings failed: ",
  saveFailed: "The deployment did not accept these values; they were left for you to correct.",
  saving: "Saving\u2026",
  save: "Save",
  discard: "Discard",
  dirty: "Unsaved changes",
  unconfigured: "No global policy is configured yet; the native defaults are shown.",
  saved: "Saved.",
  conflict: "Settings changed in another window or file; nothing was saved.",
  rejected: "Save rejected: ",
  invalid: "Invalid configuration: ",
  externalChanged: "The global configuration changed elsewhere; saving will not overwrite it \u2014 discard and reload instead.",
  mode: "Retry mode",
  parametersTitle: "Retry parameters",
  modeNormal: "Bounded retries",
  modeAlways: "Unlimited retries",
  alwaysNote: "Unlimited retries keep retrying permanent failures too, such as authentication and quota errors, until success or cancellation, and may be billed repeatedly.",
  overridden: "Overridden",
  resetToDefault: "Reset to default",
  maxRetries: "Max retries",
  maxRetriesHint: "Excludes the initial request; 0 disables ordinary retries.",
  unitRetries: "retries",
  unitMilliseconds: "ms",
  unitPercent: "%",
  initialDelayMs: "Initial delay (ms)",
  maxDelayMs: "Max delay (ms)",
  jitterPercent: "Jitter (%)",
  backoffHint: "Delay grows exponentially with jitter and never exceeds the max delay.",
  retryableCodes: "Retryable errors",
  codeDefaults: "Default codes",
  codeCustom: "Custom codes",
  customCode: "Custom error code",
  customCodePlaceholder: "for example GATEWAY_BUSY",
  add: "Add",
  removeCode: "Remove error code",
  policyHint: "RATE_LIMIT is a transient rate limit; an exhausted quota or balance is QUOTA and is not retried by default.",
  syncTitle: "Synchronization",
  syncSummary: "{synced} of {total} providers synchronized",
  syncPending: "{count} pending",
  syncAll: "All synchronized",
  syncDiffers: "Provider policy differs from the global policy",
  syncNone: "No providers",
  syncReasonSeparator: ": "
};
var dictionaries = { zh, en };
var localeKeys = Object.keys(zh);

// src/ui-style.js
var uiCss = `
.drs-section {
  max-width: 720px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  color: var(--dsw-alias-label-primary);
}

/* Page heading. The settings shell draws no title for a section page, so the
 * page keeps the official section-head structure and adds a global badge. */
.drs-titleRow {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.drs-title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  line-height: 1.4;
}

.drs-intro {
  margin: 0;
  font-size: 13px;
  line-height: 1.6;
  color: var(--dsw-alias-label-tertiary);
}

/* Tag tones follow dsh-client-ui-primitives/Tag.module.css. */
.drs-tag {
  display: inline-flex;
  align-items: center;
  border-radius: 999px;
  padding: 1px 8px;
  font-size: 11px;
  line-height: 17px;
  font-weight: 500;
  white-space: nowrap;
}

.drs-tag[data-tone='outline'] {
  border: 0.5px solid var(--dsw-alias-border-l4);
  color: var(--dsw-alias-label-tertiary);
}

.drs-tag[data-tone='neutral'] {
  background: var(--dsw-alias-bg-module-platform);
  color: var(--dsw-alias-label-secondary);
}

.drs-tag[data-tone='success'] {
  background: var(--dsw-alias-bg-layer-2);
  background: color-mix(in srgb, var(--dsw-alias-state-success-primary) 10%, transparent);
  color: var(--dsw-alias-state-success-primary);
}

.drs-tag[data-tone='warning'] {
  background: var(--dsw-alias-bg-layer-2);
  background: color-mix(in srgb, var(--dsw-alias-state-warn-primary) 12%, transparent);
  color: var(--dsw-alias-state-warn-primary);
}

.drs-tag[data-tone='danger'] {
  background: var(--dsw-alias-bg-layer-2);
  background: color-mix(in srgb, var(--dsw-alias-state-error-primary) 10%, transparent);
  color: var(--dsw-alias-state-error-primary);
}

.drs-readOnly,
.drs-unavailable {
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}

.drs-notice {
  margin: 0;
  padding: 8px 12px;
  border-radius: var(--dsw-radius-md);
  font-size: 12px;
  line-height: 1.5;
}

.drs-notice[data-tone='success'] {
  background: var(--dsw-alias-bg-layer-2);
  background: color-mix(in srgb, var(--dsw-alias-state-success-primary) 10%, transparent);
  color: var(--dsw-alias-state-success-primary);
}

.drs-notice[data-tone='info'] {
  background: var(--dsw-alias-bg-layer-2);
  background: color-mix(in srgb, var(--dsw-alias-state-business-primary) 10%, transparent);
  color: var(--dsw-alias-state-business-primary);
}

.drs-notice[data-tone='warning'] {
  background: var(--dsw-alias-bg-layer-2);
  background: color-mix(in srgb, var(--dsw-alias-state-warn-primary) 12%, transparent);
  color: var(--dsw-alias-state-warn-primary);
}

.drs-notice[data-tone='danger'] {
  background: var(--dsw-alias-bg-layer-2);
  background: color-mix(in srgb, var(--dsw-alias-state-error-primary) 10%, transparent);
  color: var(--dsw-alias-state-error-primary);
}

.drs-form {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

/* One raised settings surface, like the cards on the shipped Agent presets
 * page (\`--dsw-alias-settings-card-*\`, \`--dsw-radius-xl\`). */
.drs-panel {
  border: 0.5px solid var(--dsw-alias-settings-card-stroke, var(--dsw-alias-border-l4));
  border-radius: var(--dsw-radius-xl);
  background: var(--dsw-alias-settings-card-fill, var(--dsw-alias-bg-layer-2));
  overflow: hidden;
}

.drs-panelSection {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 16px;
}

.drs-panelSection + .drs-panelSection {
  border-top: 0.5px solid var(--dsw-alias-border-l2);
}

.drs-head {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.drs-labelGroup {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
  min-width: 0;
}

.drs-panelTitle {
  flex: 0 1 auto;
  min-width: 0;
  margin: 0;
  font-size: 13px;
  font-weight: 600;
  line-height: 1.5;
  color: var(--dsw-alias-label-primary);
}

.drs-badges {
  display: inline-flex;
  align-items: center;
  gap: 8px;
}

.drs-reset {
  border: none;
  background: none;
  padding: 0;
  font: inherit;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-secondary);
  cursor: pointer;
}

.drs-reset:hover:not(:disabled) {
  color: var(--dsw-alias-label-primary);
}

.drs-reset:disabled {
  cursor: default;
  opacity: 0.4;
}

.drs-reset:focus-visible {
  outline: var(--dsw-focus-ring-width) solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary));
  outline-offset: 2px;
}

/* Segmented control, structurally the shipped SegmentedControl: a translucent
 * track, an elevated sliding indicator positioned by custom properties, and
 * equal-width tab segments. */
.drs-segmented {
  position: relative;
  display: inline-grid;
  grid-auto-flow: column;
  grid-auto-columns: 1fr;
  gap: 2px;
  align-self: flex-start;
  padding: 4px;
  border-radius: var(--dsw-radius-md);
  background: var(--dsw-alias-interactive-bg-hover);
}

.drs-segmentedIndicator {
  position: absolute;
  top: 4px;
  left: 4px;
  width: calc((100% - 8px - 2px * (var(--drs-segment-count) - 1)) / var(--drs-segment-count));
  height: calc(100% - 8px);
  border-radius: var(--dsw-radius-sm);
  background: var(--dsw-alias-bg-layer-1);
  box-shadow: var(--dsw-elevation-soft);
  transform: translateX(calc(var(--drs-segment-index) * (100% + 2px)));
  transition: transform 160ms ease;
  pointer-events: none;
}

.drs-segment {
  box-sizing: border-box;
  position: relative;
  z-index: 1;
  height: 28px;
  padding: 0 16px;
  border: 0;
  border-radius: var(--dsw-radius-sm);
  background: transparent;
  color: var(--dsw-alias-label-secondary);
  font: inherit;
  font-size: 13px;
  line-height: 20px;
  font-weight: 500;
  white-space: nowrap;
  cursor: pointer;
  transition: color 120ms ease;
}

.drs-segment:hover:not(:disabled),
.drs-segment[aria-selected='true'] {
  color: var(--dsw-alias-label-primary);
}

.drs-segment:disabled {
  cursor: default;
  opacity: 0.4;
}

.drs-segment:focus-visible {
  outline: var(--dsw-focus-ring-width) solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary));
  outline-offset: -2px;
}

/* Numeric fields. */
.drs-numberGrid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}

.drs-field {
  display: flex;
  flex-direction: column;
  gap: 6px;
  min-width: 0;
}

.drs-label {
  font-size: 13px;
  font-weight: 500;
  line-height: 1.5;
  color: var(--dsw-alias-label-primary);
}

.drs-inputShell {
  display: flex;
  align-items: center;
  gap: 8px;
  height: 34px;
  padding: 0 12px;
  border: 0.5px solid var(--dsw-alias-border-l4);
  border-radius: var(--dsw-radius-md);
  background: var(--dsw-alias-bg-layer-3);
  transition: border-color 120ms ease;
}

.drs-inputShell:focus-within {
  border-color: var(--dsw-alias-state-business-primary);
}

.drs-inputShell[data-invalid='true'],
.drs-inputShell[data-invalid='true']:focus-within {
  border-color: var(--dsw-alias-state-error-primary);
}

.drs-input {
  flex: 1;
  min-width: 0;
  border: 0;
  outline: 0;
  background: transparent;
  font: inherit;
  font-size: 13px;
  line-height: 1.5;
  color: var(--dsw-alias-label-primary);
}

.drs-input::placeholder {
  color: var(--dsw-alias-label-dimmed);
}

.drs-input:disabled {
  color: var(--dsw-alias-label-tertiary);
  cursor: default;
}

.drs-inputUnit {
  flex: none;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}

.drs-invalid {
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-state-error-primary);
}

.drs-hint {
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}

/* Retryable codes as selectable chips: the checked state uses the same ghost
 * active fill and inset border as the shipped Pill component. */
.drs-chipList {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.drs-chip {
  position: relative;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  height: 28px;
  padding: 0 12px;
  border: 0.5px solid var(--dsw-alias-border-l4);
  border-radius: 999px;
  background: var(--dsw-alias-bg-layer-1);
  color: var(--dsw-alias-label-secondary);
  font-size: 12px;
  line-height: 18px;
  cursor: pointer;
  transition: border-color 120ms ease, background 120ms ease, color 120ms ease;
}

.drs-chip input {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  margin: 0;
  opacity: 0;
  cursor: inherit;
}

.drs-chip:hover:not(:has(input:disabled)) {
  background: var(--dsw-alias-interactive-bg-hover);
}

.drs-chip[data-checked='true'] {
  background: var(--dsw-alias-button-ghost-active-fill);
  border-color: var(--dsw-alias-button-ghost-active-border);
  color: var(--dsw-alias-label-primary);
  font-weight: 500;
}

.drs-chip:has(input:disabled) {
  cursor: default;
  opacity: 0.5;
}

.drs-chip:has(input:focus-visible) {
  outline: var(--dsw-focus-ring-width) solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary));
  outline-offset: 2px;
}

.drs-chipCustom {
  padding-right: 6px;
  font-family: var(--dsw-font-mono, ui-monospace, SFMono-Regular, Menlo, monospace);
  cursor: default;
}

.drs-chipRemove {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 18px;
  height: 18px;
  border: 0;
  border-radius: 999px;
  background: transparent;
  color: var(--dsw-alias-label-tertiary);
  font: inherit;
  font-size: 14px;
  line-height: 1;
  padding: 0;
  cursor: pointer;
}

.drs-chipRemove:hover:not(:disabled) {
  background: var(--dsw-alias-interactive-bg-hover);
  color: var(--dsw-alias-label-primary);
}

.drs-chipRemove:disabled {
  cursor: default;
  opacity: 0.4;
}

.drs-chipRemove:focus-visible {
  outline: var(--dsw-focus-ring-width) solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary));
  outline-offset: 1px;
}

.drs-addRow {
  display: flex;
  align-items: center;
  gap: 8px;
}

.drs-addRow .drs-inputShell {
  flex: 1;
  min-width: 0;
}

.drs-addRow .drs-secondaryButton {
  height: 34px;
}

/* Synchronization summary. The state dot follows StateDot's data-state tones. */
.drs-sync {
  display: flex;
  flex-direction: column;
  gap: 8px;
  border: 0.5px solid var(--dsw-alias-settings-card-stroke, var(--dsw-alias-border-l4));
  border-radius: var(--dsw-radius-xl);
  background: var(--dsw-alias-settings-card-fill, var(--dsw-alias-bg-layer-2));
  padding: 12px 16px;
}

.drs-syncHead {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.drs-stateDot {
  flex: none;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: currentColor;
}

.drs-stateDot[data-state='done'] {
  color: var(--dsw-alias-state-success-primary);
}

.drs-stateDot[data-state='warning'] {
  color: var(--dsw-alias-state-warn-primary);
}

.drs-stateDot[data-state='error'] {
  color: var(--dsw-alias-state-error-primary);
}

.drs-stateDot[data-state='idle'] {
  color: var(--dsw-alias-state-idle-primary);
}

.drs-syncTitle {
  font-size: 13px;
  font-weight: 600;
  line-height: 1.5;
  color: var(--dsw-alias-label-primary);
}

.drs-syncCount {
  margin-left: auto;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}

.drs-syncList {
  display: flex;
  flex-direction: column;
  gap: 4px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.drs-syncItem {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  margin: 0;
  font-size: 12px;
  line-height: 1.6;
  color: var(--dsw-alias-label-secondary);
}

.drs-syncProvider {
  font-family: var(--dsw-font-mono, ui-monospace, SFMono-Regular, Menlo, monospace);
  color: var(--dsw-alias-label-primary);
}

/* Buttons follow the shipped Button heights and fills. */
.drs-save {
  box-sizing: border-box;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 36px;
  padding: 0 16px;
  border: none;
  border-radius: var(--dsw-radius-md);
  background: var(--dsw-alias-button-primary-fill);
  color: var(--dsw-alias-label-primary-foreground);
  font: inherit;
  font-size: 14px;
  line-height: 22px;
  font-weight: 500;
  cursor: pointer;
}

.drs-save:hover:not(:disabled) {
  background: var(--dsw-alias-button-primary-hover);
}

.drs-save:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.drs-save:focus-visible {
  outline: var(--dsw-focus-ring-width) solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary));
  outline-offset: 1px;
}

.drs-secondaryButton {
  box-sizing: border-box;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 36px;
  padding: 0 14px;
  border: 0.5px solid var(--dsw-alias-border-l3);
  border-radius: var(--dsw-radius-md);
  background: transparent;
  color: var(--dsw-alias-label-primary);
  font: inherit;
  font-size: 14px;
  line-height: 22px;
  cursor: pointer;
}

.drs-secondaryButton:hover:not(:disabled) {
  background: var(--dsw-alias-interactive-bg-hover);
}

.drs-secondaryButton:active:not(:disabled) {
  background: var(--dsw-alias-interactive-bg-active);
}

.drs-secondaryButton:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.drs-secondaryButton:focus-visible {
  outline: var(--dsw-focus-ring-width) solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary));
  outline-offset: 1px;
}

.drs-footer {
  display: flex;
  align-items: center;
  gap: 8px;
  padding-top: 4px;
}

.drs-failed {
  flex: 1;
  min-width: 0;
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-state-error-primary);
}

.drs-dirty {
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}


/* Global-default section and per-provider override rows. */
.drs-globalSection,
.drs-providersSection {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

/* Compact synchronization summary shown above the provider-override list. */
.drs-providerSummary {
  display: flex;
  align-items: center;
  gap: 8px;
  margin: 0;
}

.drs-providerSummary .drs-hint {
  flex: 1;
  min-width: 0;
}

.drs-providerSummary .drs-syncList {
  flex-basis: 100%;
}

.drs-providerList {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.drs-providerCard {
  display: flex;
  flex-direction: column;
  gap: 8px;
  border: 0.5px solid var(--dsw-alias-settings-card-stroke, var(--dsw-alias-border-l4));
  border-radius: var(--dsw-radius-xl);
  background: var(--dsw-alias-settings-card-fill, var(--dsw-alias-bg-layer-2));
  padding: 12px 16px;
}

.drs-providerHead {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.drs-providerName {
  display: flex;
  align-items: baseline;
  gap: 6px;
  min-width: 0;
  flex: 1;
}

.drs-providerDisplayName {
  font-size: 13px;
  font-weight: 600;
  line-height: 1.5;
  color: var(--dsw-alias-label-primary);
}

.drs-providerId {
  font-family: var(--dsw-font-mono, ui-monospace, SFMono-Regular, Menlo, monospace);
  font-size: 11px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}

.drs-providerAction {
  height: 28px;
  padding: 0 10px;
  font-size: 12px;
  line-height: 18px;
  border-radius: var(--dsw-radius-sm);
}

.drs-providerEditor {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-top: 4px;
}

.drs-providerEditor .drs-footer {
  padding-top: 0;
}

.drs-providerEditor .drs-panel {
  background: var(--dsw-alias-bg-layer-1);
}

@media (max-width: 560px) {
  .drs-numberGrid {
    grid-template-columns: 1fr;
  }

  .drs-panelSection {
    padding: 14px;
  }

  .drs-segmented {
    align-self: stretch;
    width: 100%;
  }

  .drs-footer {
    flex-wrap: wrap;
  }

  .drs-failed {
    flex-basis: 100%;
  }
}

@media (prefers-reduced-motion: reduce) {
  .drs-segmentedIndicator,
  .drs-segment,
  .drs-chip,
  .drs-inputShell {
    transition: none;
  }
}
`;

// src/client.js
var inject = ["slots", "locale", "remote", "remote.settings", "remote.llm"];
var NS = "dsh-retry-settings";
function RetrySettingsSection({ useSnapshot, controller, t }) {
  const snapshot = useSnapshot((value) => value);
  return import_react2.default.createElement(
    import_react2.default.Fragment,
    null,
    import_react2.default.createElement("style", null, uiCss),
    import_react2.default.createElement(RetrySettingsView, { snapshot, actions: controller.actions, t })
  );
}
function apply(ctx) {
  ctx.effect(() => ctx.locale.register(NS, dictionaries), "dsh-retry-settings: copy dictionaries");
  const t = ctx.locale.bind(NS);
  const controller = createRetrySettingsController({ remote: ctx.remote });
  ctx.effect(() => {
    const refresh = () => {
      void controller.refresh();
    };
    const disposers = [
      ctx.remote.$on("settings/document-updated", refresh),
      ctx.remote.$on("llm/adapters-updated", refresh),
      ctx.on("connection/reset", refresh)
    ];
    return () => {
      for (const dispose of disposers) dispose();
      controller.dispose();
    };
  }, "dsh-retry-settings: forwarded setting and provider changes");
  ctx.slots.inject("settings.section", () => ctx.slots.register({
    name: "settings.section",
    id: NS,
    order: 12,
    label: () => t("nav"),
    inject: () => ({ controller, hooks: { snapshot: controller.store }, t })
  }, RetrySettingsSection));
  void controller.load().catch((error) => {
    console.error("[dsh-retry-settings] initial read failed", error);
  });
}

    return module.exports;
  }
});
