import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export async function compileClient(entry) {
  const result = await build({
    entryPoints: [entry],
    bundle: true,
    platform: 'browser',
    format: 'cjs',
    target: 'es2022',
    external: ['react'],
    write: false,
    legalComments: 'none',
  });
  return `// Generated by npm run build.\nwindow.__ModuleLoader__.load({\n  id: '@local/dsh-retry-settings',\n  factory(require) {\n    const module = { exports: {} };\n    const exports = module.exports;\n${result.outputFiles[0].text}\n    return module.exports;\n  }\n});\n`;
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  const entry = fileURLToPath(new URL('../src/client.js', import.meta.url));
  const output = new URL('../client.js', import.meta.url);
  await writeFile(output, await compileClient(entry), 'utf8');
}
